### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mssimi** [symfony-cmf/menu-bundle#290]
Hey, why is loader checking instance twice?

[https://github.com/symfony-cmf/menu-bundle/blob/master/src/Loader/VotingNodeLoader.php#L45](url)
[https://github.com/symfony-cmf/menu-bundle/blob/master/src/Loader/VotingNodeLoader.php#L74](url)

It goes throught $this->supports anyway, coz of recursion. Or is there any reason why u want to skip throwing exception?

**Comment by dbu** [comment]
hi. the loop skips children that don't implement the interface. the
document could have non-menu children and we want to ignore those. if we
would just call the recursion, we would end up with an exception

Am 17.05.2017 9:05 nachm. schrieb "Marek Šimeček" <notifications@github.com
>:

Hey, why is loader checking instance twice?

https://github.com/symfony-cmf/menu-bundle/blob/master/
src/Loader/VotingNodeLoader.php#L45 <http://url>
https://github.com/symfony-cmf/menu-bundle/blob/master/
src/Loader/VotingNodeLoader.php#L74 <http://url>

It goes throught $this->supports anyway, coz of recursion. Or is there any
reason why u want to skip throwing exception?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/symfony-cmf/menu-bundle/issues/290>, or mute the thread

**Comment by mssimi** [comment]
Sounds weird to me, why combing menu-items and non-menu items in menu. I dont see real usage, but whatever:)

**Comment by dbu** [comment]
i would not recommend it, but when it happens, whether by accident or on purpose, the site should not break.
